### ISSUE TITLE
Icon not visible if theme conflicts

### ISSUE THREAD

**Issue by MikeCraig418** [nalingia/nova-secret-field#1]
My sidebar icons are white; I didn't know how this plugin worked until I viewed the source code.

![image](https://user-images.githubusercontent.com/23151962/81002219-bb7d1300-8dfd-11ea-9f3d-90bf8c3ff5e8.png)

Please add a method to change the SVG icon color within the plugin... it will help dummies like me.

**Comment by MikeCraig418** [comment]
Another option might be to use the icon colors for the row, like the default edit, view, trash, etc.

![image](https://user-images.githubusercontent.com/23151962/81002763-a785e100-8dfe-11ea-9d81-7f3a831521de.png)

**Comment by nalingia** [comment]
Hi @949mac,
thanks for your suggestions.
Since there's no way to edit the icons' colour in other fields, I will go for standardisation to Nova's action buttons: the button will behave the same like the Nova' ones.

A fix will be available on the next patch release (1.0.5).

**Comment by nalingia** [comment]
Fixed in 1.0.5
