### ISSUE TITLE
Doesn't honor ->readonly()

### ISSUE THREAD

**Issue by MikeCraig418** [nalingia/nova-secret-field#3]
Sometimes secrets should change....

```
NovaSecretField::make('API Key', 'api_key')->readonly(),
```

Great plugin, btw! I'll give you 5 stars on Nova Packages if you can get these issues taken care of.

**Comment by nalingia** [comment]
Hi again @949mac ,
thanks for your reporting.
The issue is going to be fixed on next patch release (1.0.5).

**Comment by nalingia** [comment]
Fixed in 1.0.5
